// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mupprrjhftvxhblotcyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im11cHBycmpoZnR2eGhibG90Y3l0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NzcyODYsImV4cCI6MjA3MTM1MzI4Nn0.Tu2kKkI7L2HyYAX7J12vDdSIQVCKfN7LTY4UM1F95Rk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});